import CryptoKit
import Foundation
import Security
import SimpleKeychain
import SolanaTransactions

/// Represents an active, encrypted session between the dApp and a deeplink-based wallet.
public struct DeeplinkWalletConnection: WalletConnection {
    //Models an active, secure session between a dApp and a wallet
    public struct DiffieHellmanData: Codable {
        let publicKey: Data
        let privateKey: Data
        let sharedKey: Data

        /// Initializes a new `DiffieHellmanData` instance containing the  keys
        /// used for an encrypted session between a dApp and a wallet.
        ///
        /// - Parameters:
        ///   - publicKey: The  public key generated by the dApp. Shared with the wallet for key agreement.
        ///   - privateKey: The  private key. Used together with the wallet's public key to compute the shared key. Must be kept secret.
        ///   - sharedKey: The derived shared key used to encrypt and decrypt messages between the dApp and the wallet.
        public init(publicKey: Data, privateKey: Data, sharedKey: Data) {
            self.publicKey = publicKey
            self.privateKey = privateKey
            self.sharedKey = sharedKey
        }
    }

    public let session: String
    public let encryption: DiffieHellmanData
    public let publicKey: PublicKey

    /// Initializes a new `DeeplinkWalletConnection`.
    ///
    /// - Parameters:
    ///   - session: A session identifier generated by the wallet upon
    ///     user approval through the `connect` method.
    ///   - encryption: The encryption of the public, private and shared key used to encrypt and decrypt messages between the dApp and wallet.. See ``DiffieHellmanData``.
    ///   - walletPublicKey: The public key of the wallet
    public init(
        session: String,
        encryption: DiffieHellmanData,
        walletPublicKey: PublicKey
    ) {
        self.session = session
        self.encryption = encryption
        self.publicKey = walletPublicKey
    }
}
